name: basemodels
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - matplotlib==3.5.3
      - numpy==1.24.3
      - pandas==2.2.3
      - scikit-learn==1.6.0
      - seaborn==0.13.2
      - tensorflow==2.11.0
      - tensorflow-addons==0.22.0
      - vit-keras
      - opencv-python